name: Build and Deploy Preview

on:
  push:
    branches: [preview]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install ImageMagick and Jupyter
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick
          python3 -m pip install --upgrade pip
          pip install notebook

      - run: gem install bundler
      - run: bundle install

      - run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
